image: maven:3.9.9-eclipse-temurin-21   #  Maven 3.9.9 und Java 21

stages:          
  - build
  - test
  - deploy

# Build-Job
build-job:
  stage: build
  script:
    - echo "Building the Java application..."
    - mvn clean compile   # Kompiliere das Projekt
  artifacts:
    paths:
      - target/   # Speichert das gebaute Artefakt (target-Verzeichnis)

# Test-Job
unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - mvn test   # Führe Unit-Tests mit Maven aus
  artifacts:
    when: always
    paths:
      - target/surefire-reports/   # Speichert die Testberichte (Surefire-Berichte)
    reports:
      junit: target/surefire-reports/*.xml  # Speichert die JUnit-Testergebnisse

# Linting-Job
lint-job:
  stage: test
  script:
    - echo "Running Checkstyle Linting..."
    - mvn checkstyle:checkstyle   # Führe das Linting mit Checkstyle durch
  artifacts:
    when: always
    paths:
      - target/checkstyle-result.xml   # Speichert die Linter-Ergebnisse





# Deployment-Job
deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  only:
    - main
