name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Dieser Cron-Job läuft alle 5 Minuten.
    - cron: '*/5 * * * *'

jobs:
  check-run-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Schritt 1: Lade die Datei, die den Zähler speichert
      - name: Check the run count
        id: check_count
        run: |
          if [ -f run_count.txt ]; then
            count=$(cat run_count.txt)
            echo "Run count is $count"
          else
            count=0
            echo "No count found, initializing with 0"
          fi
          
          # Breche den Workflow ab, wenn er 100 Mal ausgeführt wurde
          if [ "$count" -ge 100 ]; then
            echo "The workflow has already run 100 times, stopping."
            exit 0
          fi
          
          # Inkrementiere den Zähler um 1
          new_count=$((count + 1))
          echo $new_count > run_count.txt
          echo "The new run count is $new_count"
      
      # Schritt 2: Committe den aktualisierten Zähler zurück in das Repository
      - name: Commit new run count
        env:
          TOKEN: ${{ secrets.johanna_TOKEN}}  #johanna_TOKEN
        run: |
          git config --global user.name "Johanna0815"
          git config --global user.email "if20b016@technikum-wien.at"
          git add run_count.txt
          git commit -m "Update run count to $new_count"
          git push https://x-access-token:${TOKEN}@github.com/Johanna0815/JAVAII_Konsolenanwendung.git
